- ignore: {name: Eta reduce}
- ignore: {name: Use if}
- ignore: {name: Unnecessary hiding}
- ignore: {name: Use readTVarIO}


# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
