- ignore: {name: Eta reduce}
- ignore: {name: Use if}
- ignore: {name: Unnecessary hiding}
- ignore: {name: Use readTVarIO}
- ignore: {name: Reduce duplication}
- ignore: {name: Use tuple-section}
- ignore: {name: Redundant flip}

# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
