name: etc
version: '0.0.1.0'
synopsis: etc
description: emit - transduce - commit
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/etc
extra-source-files:
- stack.yaml
- readme.md
dependencies:
- base >=4.7 && <5
library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -funbox-strict-fields
  exposed-modules:
  - Etc
  - Etc.Action
  - Etc.Broadcast
  - Etc.Managed
  - Etc.Time
  - Etc.Updater
  dependencies:
  - async
  - attoparsec
  - contravariant
  - data-default
  - flow
  - foldl
  - lens
  - pipes
  - profunctors
  - protolude
  - stm
  - streaming 
  - text
  - time
  - transformers
  - transformers-base
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - doctest
    - protolude
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
