name: box
version: '0.0.1.1'
synopsis: boxes
description: concurrent, effectful boxes
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/box
extra-source-files:
  - stack.yaml
  - readme.md
dependencies:
  - base >=4.7 && <5
library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -funbox-strict-fields
  exposed-modules:
    - Box
    - Box.Action
    - Box.Box
    - Box.Broadcast
    - Box.Committer
    - Box.Connectors
    - Box.Cont
    - Box.Emitter
    - Box.IO
    - Box.Plugs
    - Box.Queue
    - Box.Stream
    - Box.Time
    - Box.Transducer
    - Box.Updater
  dependencies:
  - async
  - attoparsec
  - concurrency
  - contravariant
  - data-default
  - dejafu
  - exceptions
  - flow
  - foldl
  - generic-lens-labels
  - generic-lens
  - lens
  - mmorph
  - pipes
  - profunctors
  - protolude
  - random
  - stm
  - streaming 
  - text
  - time
  - transformers
  - transformers-base
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - box
      - async
      - attoparsec
      - concurrency
      - contravariant
      - data-default
      - dejafu
      - exceptions
      - flow
      - foldl
      - generic-lens
      - generic-lens-labels
      - lens
      - mmorph
      - pipes
      - profunctors
      - protolude
      - random
      - stm
      - streaming 
      - text
      - time
      - transformers
      - transformers-base
      - doctest
      - protolude
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
