name: etc
version: '0.0.1.0'
synopsis: etc
description: emit - transduce - commit
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/etc
extra-source-files:
- stack.yaml
- readme.md
dependencies:
- base >=4.7 && <5
library:
  source-dirs: src
  ghc-options:
  - -funbox-strict-fields
  - -fforce-recomp
  exposed-modules:
  - Etc
  dependencies:
  - contravariant
  - flow
  - foldl
  - managed
  - pipes-concurrency
  - profunctors
  - protolude
  - streaming
  - text
  - transformers
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - doctest
    - protolude
